/**
 * This module vendors the data fetched from ISO 3166-1 catalog.  Those data
 * are automatically fetched and replaced by the build process.
 */

/*
 * NOTE that the comments look like the following in the source code are
 * placeholders for the build process:
 *
 *     // TERM //
 *     ...
 *     // END TERM //
 *
 * Therefore, you should not edit the comments and the lines between them by
 * hand.  There are 4 terms in this file: UPDATED DATE, CODES, LABEL LANGUAGES,
 * and LABELS.  The build process replaces the contents for each term with the
 * actual data.
 */

/**
 * The date when the data were last updated.  In other words, this date means
 * the version of the data.  Note that the time part of this object is mostly
 * meaningless.
 */
export const updatedDate: Date = new Date(
  // UPDATED DATE //
  "2009-09-01T04:00:00.000Z",
  // END UPDATED DATE //
);

/**
 * The array of all valid language codes.  This array contains only the
 * two-letter language codes defined in ISO 3166-1 with lower case.
 * @constant
 */
export const languageCodes = [
  // CODES //
  "aa",
  "ab",
  "ae",
  "af",
  "ak",
  "am",
  "an",
  "ar",
  "as",
  "av",
  "ay",
  "az",
  "ba",
  "be",
  "bg",
  "bh",
  "bi",
  "bm",
  "bn",
  "bo",
  "br",
  "bs",
  "ca",
  "ce",
  "ch",
  "co",
  "cr",
  "cs",
  "cu",
  "cv",
  "cy",
  "da",
  "de",
  "dv",
  "dz",
  "ee",
  "el",
  "en",
  "eo",
  "es",
  "et",
  "eu",
  "fa",
  "ff",
  "fi",
  "fj",
  "fo",
  "fr",
  "fy",
  "ga",
  "gd",
  "gl",
  "gn",
  "gu",
  "gv",
  "ha",
  "he",
  "hi",
  "ho",
  "hr",
  "ht",
  "hu",
  "hy",
  "hz",
  "ia",
  "id",
  "ie",
  "ig",
  "ii",
  "ik",
  "io",
  "is",
  "it",
  "iu",
  "ja",
  "jv",
  "ka",
  "kg",
  "ki",
  "kj",
  "kk",
  "kl",
  "km",
  "kn",
  "ko",
  "kr",
  "ks",
  "ku",
  "kv",
  "kw",
  "ky",
  "la",
  "lb",
  "lg",
  "li",
  "ln",
  "lo",
  "lt",
  "lu",
  "lv",
  "mg",
  "mh",
  "mi",
  "mk",
  "ml",
  "mn",
  "mr",
  "ms",
  "mt",
  "my",
  "na",
  "nb",
  "nd",
  "ne",
  "ng",
  "nl",
  "nn",
  "no",
  "nr",
  "nv",
  "ny",
  "oc",
  "oj",
  "om",
  "or",
  "os",
  "pa",
  "pi",
  "pl",
  "ps",
  "pt",
  "qu",
  "rm",
  "rn",
  "ro",
  "ru",
  "rw",
  "sa",
  "sc",
  "sd",
  "se",
  "sg",
  "si",
  "sk",
  "sl",
  "sm",
  "sn",
  "so",
  "sq",
  "sr",
  "ss",
  "st",
  "su",
  "sv",
  "sw",
  "ta",
  "te",
  "tg",
  "th",
  "ti",
  "tk",
  "tl",
  "tn",
  "to",
  "tr",
  "ts",
  "tt",
  "tw",
  "ty",
  "ug",
  "uk",
  "ur",
  "uz",
  "ve",
  "vi",
  "vo",
  "wa",
  "wo",
  "xh",
  "yi",
  "yo",
  "za",
  "zh",
  "zu",
  // END CODES //
] as const;

/**
 * The array of language codes, which are valid authoritative label language.
 * @constant
 */
export const authoritativeLabelLanguages = [
  // LABEL LANGUAGES //
  "de",
  "en",
  "fr",
  // END LABEL LANGUAGES //
] as const;

/**
 * The authoritative labels of all valid language codes.  The first dimension
 * is the language code, and the second dimension is the authoritative label
 * language code.  For example, `authoritativeLabels.en.fr` is `"anglais"`,
 * which means English in French, and `authoritativeLabels.fr.de` is
 * `"Französisch"`, which means French in German.
 * @constant
 */
export const authoritativeLabels: Record<
  typeof languageCodes[number],
  Record<typeof authoritativeLabelLanguages[number], string>
> = {
  // cSpell:disable
  // LABELS //
  "aa": { "en": "Afar", "fr": "afar", "de": "Danakil-Sprache" },
  "ab": { "en": "Abkhazian", "fr": "abkhaze", "de": "Abchasisch" },
  "ae": { "en": "Avestan", "fr": "avestique", "de": "Avestisch" },
  "af": { "en": "Afrikaans", "fr": "afrikaans", "de": "Afrikaans" },
  "ak": { "en": "Akan", "fr": "akan", "de": "Akan-Sprache" },
  "am": { "en": "Amharic", "fr": "amharique", "de": "Amharisch" },
  "an": { "en": "Aragonese", "fr": "aragonais", "de": "Aragonesisch" },
  "ar": { "en": "Arabic", "fr": "arabe", "de": "Arabisch" },
  "as": { "en": "Assamese", "fr": "assamais", "de": "Assamesisch" },
  "av": { "en": "Avaric", "fr": "avar", "de": "Awarisch" },
  "ay": { "en": "Aymara", "fr": "aymara", "de": "Aymará-Sprache" },
  "az": { "en": "Azerbaijani", "fr": "azéri", "de": "Aserbeidschanisch" },
  "ba": { "en": "Bashkir", "fr": "bachkir", "de": "Baschkirisch" },
  "be": { "en": "Belarusian", "fr": "biélorusse", "de": "Weißrussisch" },
  "bg": { "en": "Bulgarian", "fr": "bulgare", "de": "Bulgarisch" },
  "bh": {
    "en": "Bihari languages",
    "fr": "langues biharis",
    "de": "Bihari (Andere)",
  },
  "bi": { "en": "Bislama", "fr": "bichlamar", "de": "Beach-la-mar" },
  "bm": { "en": "Bambara", "fr": "bambara", "de": "Bambara-Sprache" },
  "bn": { "en": "Bengali", "fr": "bengali", "de": "Bengali" },
  "bo": { "en": "Tibetan", "fr": "tibétain", "de": "Tibetisch" },
  "br": { "en": "Breton", "fr": "breton", "de": "Bretonisch" },
  "bs": { "en": "Bosnian", "fr": "bosniaque", "de": "Bosnisch" },
  "ca": {
    "en": "Catalan |  Valencian",
    "fr": "catalan |  valencien",
    "de": "Katalanisch",
  },
  "ce": { "en": "Chechen", "fr": "tchétchène", "de": "Tschetschenisch" },
  "ch": { "en": "Chamorro", "fr": "chamorro", "de": "Chamorro-Sprache" },
  "co": { "en": "Corsican", "fr": "corse", "de": "Korsisch" },
  "cr": { "en": "Cree", "fr": "cree", "de": "Cree-Sprache" },
  "cs": { "en": "Czech", "fr": "tchèque", "de": "Tschechisch" },
  "cu": {
    "en":
      "Church Slavic |  Old Slavonic |  Church Slavonic |  Old Bulgarian |  Old Church Slavonic",
    "fr":
      "slavon d'église |  vieux slave |  slavon liturgique |  vieux bulgare",
    "de": "Kirchenslawisch",
  },
  "cv": { "en": "Chuvash", "fr": "tchouvache", "de": "Tschuwaschisch" },
  "cy": { "en": "Welsh", "fr": "gallois", "de": "Kymrisch" },
  "da": { "en": "Danish", "fr": "danois", "de": "Dänisch" },
  "de": { "en": "German", "fr": "allemand", "de": "Deutsch" },
  "dv": {
    "en": "Divehi |  Dhivehi |  Maldivian",
    "fr": "maldivien",
    "de": "Maledivisch",
  },
  "dz": { "en": "Dzongkha", "fr": "dzongkha", "de": "Dzongkha" },
  "ee": { "en": "Ewe", "fr": "éwé", "de": "Ewe-Sprache" },
  "el": {
    "en": "Greek, Modern (1453-)",
    "fr": "grec moderne (après 1453)",
    "de": "Neugriechisch",
  },
  "en": { "en": "English", "fr": "anglais", "de": "Englisch" },
  "eo": { "en": "Esperanto", "fr": "espéranto", "de": "Esperanto" },
  "es": {
    "en": "Spanish |  Castilian",
    "fr": "espagnol |  castillan",
    "de": "Spanisch",
  },
  "et": { "en": "Estonian", "fr": "estonien", "de": "Estnisch" },
  "eu": { "en": "Basque", "fr": "basque", "de": "Baskisch" },
  "fa": { "en": "Persian", "fr": "persan", "de": "Persisch" },
  "ff": { "en": "Fulah", "fr": "peul", "de": "Ful" },
  "fi": { "en": "Finnish", "fr": "finnois", "de": "Finnisch" },
  "fj": { "en": "Fijian", "fr": "fidjien", "de": "Fidschi-Sprache" },
  "fo": { "en": "Faroese", "fr": "féroïen", "de": "Färöisch" },
  "fr": { "en": "French", "fr": "français", "de": "Französisch" },
  "fy": {
    "en": "Western Frisian",
    "fr": "frison occidental",
    "de": "Friesisch",
  },
  "ga": { "en": "Irish", "fr": "irlandais", "de": "Irisch" },
  "gd": {
    "en": "Gaelic |  Scottish Gaelic",
    "fr": "gaélique |  gaélique écossais",
    "de": "Gälisch-Schottisch",
  },
  "gl": { "en": "Galician", "fr": "galicien", "de": "Galicisch" },
  "gn": { "en": "Guarani", "fr": "guarani", "de": "Guaraní-Sprache" },
  "gu": { "en": "Gujarati", "fr": "goudjrati", "de": "Gujarati-Sprache" },
  "gv": { "en": "Manx", "fr": "manx |  mannois", "de": "Manx" },
  "ha": { "en": "Hausa", "fr": "haoussa", "de": "Haussa-Sprache" },
  "he": { "en": "Hebrew", "fr": "hébreu", "de": "Hebräisch" },
  "hi": { "en": "Hindi", "fr": "hindi", "de": "Hindi" },
  "ho": { "en": "Hiri Motu", "fr": "hiri motu", "de": "Hiri-Motu" },
  "hr": { "en": "Croatian", "fr": "croate", "de": "Kroatisch " },
  "ht": {
    "en": "Haitian |  Haitian Creole",
    "fr": "haïtien |  créole haïtien",
    "de": "Haïtien (Haiti-Kreolisch)",
  },
  "hu": { "en": "Hungarian", "fr": "hongrois", "de": "Ungarisch" },
  "hy": { "en": "Armenian", "fr": "arménien", "de": "Armenisch" },
  "hz": { "en": "Herero", "fr": "herero", "de": "Herero-Sprache" },
  "ia": {
    "en": "Interlingua (International Auxiliary Language Association)",
    "fr": "interlingua (langue auxiliaire internationale)",
    "de": "Interlingua",
  },
  "id": { "en": "Indonesian", "fr": "indonésien", "de": "Bahasa Indonesia" },
  "ie": {
    "en": "Interlingue |  Occidental",
    "fr": "interlingue",
    "de": "Interlingue",
  },
  "ig": { "en": "Igbo", "fr": "igbo", "de": "Ibo-Sprache" },
  "ii": {
    "en": "Sichuan Yi |  Nuosu",
    "fr": "yi de Sichuan",
    "de": "Lalo-Sprache",
  },
  "ik": { "en": "Inupiaq", "fr": "inupiaq", "de": "Inupik" },
  "io": { "en": "Ido", "fr": "ido", "de": "Ido" },
  "is": { "en": "Icelandic", "fr": "islandais", "de": "Isländisch" },
  "it": { "en": "Italian", "fr": "italien", "de": "Italienisch" },
  "iu": { "en": "Inuktitut", "fr": "inuktitut", "de": "Inuktitut" },
  "ja": { "en": "Japanese", "fr": "japonais", "de": "Japanisch" },
  "jv": { "en": "Javanese", "fr": "javanais", "de": "Javanisch" },
  "ka": { "en": "Georgian", "fr": "géorgien", "de": "Georgisch" },
  "kg": { "en": "Kongo", "fr": "kongo", "de": "Kongo-Sprache" },
  "ki": { "en": "Kikuyu |  Gikuyu", "fr": "kikuyu", "de": "Kikuyu-Sprache" },
  "kj": {
    "en": "Kuanyama |  Kwanyama",
    "fr": "kuanyama |  kwanyama",
    "de": "Kwanyama-Sprache",
  },
  "kk": { "en": "Kazakh", "fr": "kazakh", "de": "Kasachisch" },
  "kl": {
    "en": "Kalaallisut |  Greenlandic",
    "fr": "groenlandais",
    "de": "Grönländisch",
  },
  "km": {
    "en": "Central Khmer",
    "fr": "khmer central",
    "de": "Kambodschanisch",
  },
  "kn": { "en": "Kannada", "fr": "kannada", "de": "Kannada" },
  "ko": { "en": "Korean", "fr": "coréen", "de": "Koreanisch" },
  "kr": { "en": "Kanuri", "fr": "kanouri", "de": "Kanuri-Sprache" },
  "ks": { "en": "Kashmiri", "fr": "kashmiri", "de": "Kaschmiri" },
  "ku": { "en": "Kurdish", "fr": "kurde", "de": "Kurdisch" },
  "kv": { "en": "Komi", "fr": "kom", "de": "Komi-Sprache" },
  "kw": { "en": "Cornish", "fr": "cornique", "de": "Kornisch" },
  "ky": { "en": "Kirghiz |  Kyrgyz", "fr": "kirghiz", "de": "Kirgisisch" },
  "la": { "en": "Latin", "fr": "latin", "de": "Latein" },
  "lb": {
    "en": "Luxembourgish |  Letzeburgesch",
    "fr": "luxembourgeois",
    "de": "Luxemburgisch",
  },
  "lg": { "en": "Ganda", "fr": "ganda", "de": "Ganda-Sprache" },
  "li": {
    "en": "Limburgan |  Limburger |  Limburgish",
    "fr": "limbourgeois",
    "de": "Limburgisch",
  },
  "ln": { "en": "Lingala", "fr": "lingala", "de": "Lingala" },
  "lo": { "en": "Lao", "fr": "lao", "de": "Laotisch" },
  "lt": { "en": "Lithuanian", "fr": "lituanien", "de": "Litauisch" },
  "lu": {
    "en": "Luba-Katanga",
    "fr": "luba-katanga",
    "de": "Luba-Katanga-Sprache",
  },
  "lv": { "en": "Latvian", "fr": "letton", "de": "Lettisch" },
  "mg": { "en": "Malagasy", "fr": "malgache", "de": "Malagassi-Sprache" },
  "mh": { "en": "Marshallese", "fr": "marshall", "de": "Marschallesisch" },
  "mi": { "en": "Maori", "fr": "maori", "de": "Maori-Sprache" },
  "mk": { "en": "Macedonian", "fr": "macédonien", "de": "Makedonisch" },
  "ml": { "en": "Malayalam", "fr": "malayalam", "de": "Malayalam" },
  "mn": { "en": "Mongolian", "fr": "mongol", "de": "Mongolisch" },
  "mr": { "en": "Marathi", "fr": "marathe", "de": "Marathi" },
  "ms": { "en": "Malay", "fr": "malais", "de": "Malaiisch" },
  "mt": { "en": "Maltese", "fr": "maltais", "de": "Maltesisch" },
  "my": { "en": "Burmese", "fr": "birman", "de": "Birmanisch" },
  "na": { "en": "Nauru", "fr": "nauruan", "de": "Nauruanisch" },
  "nb": {
    "en": "Bokmål, Norwegian |  Norwegian Bokmål",
    "fr": "norvégien bokmål",
    "de": "Bokmål",
  },
  "nd": {
    "en": "Ndebele, North |  North Ndebele",
    "fr": "ndébélé du Nord",
    "de": "Ndebele-Sprache (Simbabwe)",
  },
  "ne": { "en": "Nepali", "fr": "népalais", "de": "Nepali" },
  "ng": { "en": "Ndonga", "fr": "ndonga", "de": "Ndonga" },
  "nl": {
    "en": "Dutch |  Flemish",
    "fr": "néerlandais |  flamand",
    "de": "Niederländisch",
  },
  "nn": {
    "en": "Norwegian Nynorsk |  Nynorsk, Norwegian",
    "fr": "norvégien nynorsk |  nynorsk, norvégien",
    "de": "Nynorsk",
  },
  "no": { "en": "Norwegian", "fr": "norvégien", "de": "Norwegisch" },
  "nr": {
    "en": "Ndebele, South |  South Ndebele",
    "fr": "ndébélé du Sud",
    "de": "Ndebele-Sprache (Transvaal)",
  },
  "nv": { "en": "Navajo |  Navaho", "fr": "navaho", "de": "Navajo-Sprache" },
  "ny": {
    "en": "Chichewa |  Chewa |  Nyanja",
    "fr": "chichewa |  chewa |  nyanja",
    "de": "Nyanja-Sprache",
  },
  "oc": {
    "en": "Occitan (post 1500)",
    "fr": "occitan (après 1500)",
    "de": "Okzitanisch",
  },
  "oj": { "en": "Ojibwa", "fr": "ojibwa", "de": "Ojibwa-Sprache" },
  "om": { "en": "Oromo", "fr": "galla", "de": "Galla-Sprache" },
  "or": { "en": "Oriya", "fr": "oriya", "de": "Oriya-Sprache" },
  "os": { "en": "Ossetian |  Ossetic", "fr": "ossète", "de": "Ossetisch" },
  "pa": {
    "en": "Panjabi |  Punjabi",
    "fr": "pendjabi",
    "de": "Pandschabi-Sprache",
  },
  "pi": { "en": "Pali", "fr": "pali", "de": "Pali" },
  "pl": { "en": "Polish", "fr": "polonais", "de": "Polnisch" },
  "ps": { "en": "Pushto |  Pashto", "fr": "pachto", "de": "Paschtu" },
  "pt": { "en": "Portuguese", "fr": "portugais", "de": "Portugiesisch" },
  "qu": { "en": "Quechua", "fr": "quechua", "de": "Quechua-Sprache" },
  "rm": { "en": "Romansh", "fr": "romanche", "de": "Rätoromanisch" },
  "rn": { "en": "Rundi", "fr": "rundi", "de": "Rundi-Sprache" },
  "ro": {
    "en": "Romanian |  Moldavian |  Moldovan",
    "fr": "roumain |  moldave",
    "de": "Rumänisch",
  },
  "ru": { "en": "Russian", "fr": "russe", "de": "Russisch" },
  "rw": { "en": "Kinyarwanda", "fr": "rwanda", "de": "Rwanda-Sprache" },
  "sa": { "en": "Sanskrit", "fr": "sanskrit", "de": "Sanskrit" },
  "sc": { "en": "Sardinian", "fr": "sarde", "de": "Sardisch" },
  "sd": { "en": "Sindhi", "fr": "sindhi", "de": "Sindhi-Sprache" },
  "se": { "en": "Northern Sami", "fr": "sami du Nord", "de": "Nordsaamisch" },
  "sg": { "en": "Sango", "fr": "sango", "de": "Sango-Sprache" },
  "si": {
    "en": "Sinhala |  Sinhalese",
    "fr": "singhalais",
    "de": "Singhalesisch",
  },
  "sk": { "en": "Slovak", "fr": "slovaque", "de": "Slowakisch" },
  "sl": { "en": "Slovenian", "fr": "slovène", "de": "Slowenisch" },
  "sm": { "en": "Samoan", "fr": "samoan", "de": "Samoanisch" },
  "sn": { "en": "Shona", "fr": "shona", "de": "Schona-Sprache" },
  "so": { "en": "Somali", "fr": "somali", "de": "Somali" },
  "sq": { "en": "Albanian", "fr": "albanais", "de": "Albanisch" },
  "sr": { "en": "Serbian", "fr": "serbe", "de": "Serbisch " },
  "ss": { "en": "Swati", "fr": "swati", "de": "Swasi-Sprache" },
  "st": {
    "en": "Sotho, Southern",
    "fr": "sotho du Sud",
    "de": "Süd-Sotho-Sprache",
  },
  "su": { "en": "Sundanese", "fr": "soundanais", "de": "Sundanesisch" },
  "sv": { "en": "Swedish", "fr": "suédois", "de": "Schwedisch" },
  "sw": { "en": "Swahili", "fr": "swahili", "de": "Swahili" },
  "ta": { "en": "Tamil", "fr": "tamoul", "de": "Tamil" },
  "te": { "en": "Telugu", "fr": "télougou", "de": "Telugu-Sprache" },
  "tg": { "en": "Tajik", "fr": "tadjik", "de": "Tadschikisch" },
  "th": { "en": "Thai", "fr": "thaï", "de": "Thailändisch" },
  "ti": { "en": "Tigrinya", "fr": "tigrigna", "de": "Tigrinja-Sprache" },
  "tk": { "en": "Turkmen", "fr": "turkmène", "de": "Turkmenisch" },
  "tl": { "en": "Tagalog", "fr": "tagalog", "de": "Tagalog" },
  "tn": { "en": "Tswana", "fr": "tswana", "de": "Tswana-Sprache" },
  "to": {
    "en": "Tonga (Tonga Islands)",
    "fr": "tongan (Îles Tonga)",
    "de": "Tongaisch",
  },
  "tr": { "en": "Turkish", "fr": "turc", "de": "Türkisch" },
  "ts": { "en": "Tsonga", "fr": "tsonga", "de": "Tsonga-Sprache" },
  "tt": { "en": "Tatar", "fr": "tatar", "de": "Tatarisch" },
  "tw": { "en": "Twi", "fr": "twi", "de": "Twi-Sprache" },
  "ty": { "en": "Tahitian", "fr": "tahitien", "de": "Tahitisch" },
  "ug": { "en": "Uighur |  Uyghur", "fr": "ouïgour", "de": "Uigurisch" },
  "uk": { "en": "Ukrainian", "fr": "ukrainien", "de": "Ukrainisch" },
  "ur": { "en": "Urdu", "fr": "ourdou", "de": "Urdu" },
  "uz": { "en": "Uzbek", "fr": "ouszbek", "de": "Usbekisch" },
  "ve": { "en": "Venda", "fr": "venda", "de": "Venda-Sprache" },
  "vi": { "en": "Vietnamese", "fr": "vietnamien", "de": "Vietnamesisch" },
  "vo": { "en": "Volapük", "fr": "volapük", "de": "Volapük" },
  "wa": { "en": "Walloon", "fr": "wallon", "de": "Wallonisch" },
  "wo": { "en": "Wolof", "fr": "wolof", "de": "Wolof-Sprache" },
  "xh": { "en": "Xhosa", "fr": "xhosa", "de": "Xhosa-Sprache" },
  "yi": { "en": "Yiddish", "fr": "yiddish", "de": "Jiddisch" },
  "yo": { "en": "Yoruba", "fr": "yoruba", "de": "Yoruba-Sprache" },
  "za": { "en": "Zhuang |  Chuang", "fr": "zhuang |  chuang", "de": "Zhuang" },
  "zh": { "en": "Chinese", "fr": "chinois", "de": "Chinesisch" },
  "zu": { "en": "Zulu", "fr": "zoulou", "de": "Zulu-Sprache" },
  // END LABELS //
  // cSpell:enable
};
