name: main
on:
  push:
    branches: "*"
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # cSpell: ignore allenevans
    - uses: allenevans/set-env@v2.0.0
      with:
        DENO_DIR: ${{ runner.temp }}/deno
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - uses: actions/cache@v3
      with:
        path: ${{ env.DENO_DIR }}
        key: ${{ hashFiles('deno.lock') }}
    - run: deno task lcov
    - uses: codecov/codecov-action@v3
      with:
        files: .cov-profile/cov.lcov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - run: deno check examples/*.ts mod.ts tests/*.ts
    - run: deno lint
    - run: deno fmt --check

  publish:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: [test]
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - run: deno publish
